# Site settings
title: Extempore
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://extemporelang.github.io" # the base hostname & protocol for your site
permalink: /:categories/:title/
github_username: extemporelang

# Build settings
markdown: kramdown
highlighter: pygments