# Site settings
title: Extempore
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://extemporelang.github.io" # the base hostname & protocol for your site
permalink: /:categories/:title/
github_username: extemporelang

collections:
  docs:
    output: true
  guides:
    output: true

defaults:
  -
    scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
  -
    scope:
      path: ""
      type: "guides"
    values:
      layout: "docs"

# Build settings
markdown: kramdown
highlighter: pygments
